import type { Metadata } from "next";
import { Poppins, Oswald } from "next/font/google";
import "./globals.css";
// import Header from "@/components/ui/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const oswald = Oswald({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pick weights you need
  variable: "--font-oswald", // optional (useful with Tailwind)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${oswald.variable} antialiased`}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
